language: python
python:
- 3.5

# blocklist
branches:
  except:
  - master

install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels conda-forge # For sphinxcontrib.autoprogram
- conda update -q conda
- conda info -a
- conda create -y -q -n convert python=$TRAVIS_PYTHON_VERSION jupyter nbconvert pyyaml
- pip install git+https://github.com/tonyfast/literacy
- source activate convert

script:
- set -e
- git init
- git config user.name "T-Bone"
- git config user.email "tony.fast@gmail.com"
- git remote add upstream "https://$GH_TOKEN@github.com/foreverwhatever/foreverwhatever.github.io"
- git fetch upstream
- git reset upstream/build
- git checkout master
- ipython setup.py convert
- git add _posts/*.md whatever/*.py
- git commit -m "Convert posts and scripts automatically"
- git push -q upstream HEAD:master

env:
    global:
    - secure: "HtxfYJqfHoGJ76be5EIx5907JiOpPZYPg+M3lENUnGpvA6tg9qVFV/fmiqBKKQlSTCz/GyjM4/WdRGWOEXK5g7YpuM/cpc5UpehTnbMAHnE9yAmMXMZDDhDn8rpjDhOBZIHg43i1f01Lm/ugIWvpXCqFnwVQrdeyOV18Rl30WBkBY0QqHf49plA3kEjeWqHLw7dZisRxwLRZ1Pxf/73fgdGfr6k7Rko5oJ7mIPb41NoWg1bcuzxVi1IjOdX3TFT1RNpE1n1IMTPGZGOge+UwsZYAbmXQBkfDCePP6GAbsXuYg3jHjLlrNebKIKsLch0Pb4ZJuYsNS7p9m8odLdSz2q5RarV4v25OK9fPlLuE60IlH1QQowFnKDftm9mQplUhiqYesSlGC5QuLum8GStY580prIlQB7PIi3jTaskSAreMz/WBkagp1RnKkq/lzDjzWvHtVW4K8v14G/3df+FRuSOOBzl4Jw7h6NHx2CGsAs3VzMQQTEPD6hdSpHE9wHLAS3OMFpZKK5uUhgCr61BssSfpIQ5Xxj9Dblr8g23BO11/ORgtxMN3yrSv6f+QaTup5Ca0hqBeOBH2XAgSllquF+O+CGgZMJY8VqGJyYAMF0+hhqlj/jpEswLYakKGFujLtz5txZutQG0qUQ1U7X2MCgCZwObYPg2n9FAY+LqFUlU="
