// Generated by CoffeeScript 1.11.1
if (window.fader_callback == null) {
  window.fader_callback = function(x, y, renderer) {
    var dx, prop, ref, results, t, updated, value;
    dx = x.end - x.start;
    ref = window.scrolling[renderer.id];
    results = [];
    for (prop in ref) {
      value = ref[prop];
      t = dx / (value.lim[1] - value.lim[0]);
      if ((0 < t && t < 1)) {
        updated = (1 - t) * value.value[0] + t * value.value[1];
        if (value['append'] != null) {
          updated += value.append;
        }
        results.push(renderer.glyph.set(prop, updated));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };
}
