// Generated by CoffeeScript 1.11.1
var base, name;

if (window.scrolling == null) {
  window.scrolling = {};
}

if ((base = window.scrolling)[name = renderer.id] == null) {
  base[name] = {{props}};
}
